Entity/Player.php
<?php

namespace Bundle\LichessBundle\Entity;

use Bundle\LichessBundle\Model;

/**
 * Represents a single Chess player for one game
 *
 * @orm:Entity
 * @author     Thibault Duplessis <thibault.duplessis@gmail.com>
 */
class Player extends Model\Player
{
    /**
     * Unique ID of the player for this game
     *
     * @var string
     * @orm:Id
     * @orm:Column(type="string")
     */
    protected $id;

    /**
     * User bound to the player - optional
     *
     * @var User
     * @orm:ManyToOne(targetEntity="Application\DoctrineUserBundle\Entity\User")
     */
    protected $user = null;

    /**
     * Fixed ELO of the player user, if any
     *
     * @var int
     * @orm:Column(type="integer", nullable=true)
     */
    protected $elo = null;

    /**
     * the player color, white or black
     *
     * @var string
     * @orm:Column(type="string")
     */
    protected $color;

    /**
     * Whether the player won the game or not
     *
     * @var boolean
     * @orm:Column(type="boolean")
     */
    protected $isWinner = false;

    /**
     * Whether this player is an Artificial intelligence or not
     *
     * @var boolean
     * @orm:Column(type="boolean")
     */
    protected $isAi = false;

    /**
     * If the player is an AI, its level represents the AI intelligence
     *
     * @var int
     * @orm:Column(type="integer", nullable=true)
     */
    protected $aiLevel;

    /**
     * Event stack
     *
     * @var Stack
     * @orm:OneToOne(targetEntity="Stack", cascade={"persist", "remove"})
     */
    protected $stack;

    /**
     * the player pieces
     *
     * @var Collection
     * @orm:OneToMany(targetEntity="Piece", mappedBy="player", cascade={"persist", "remove"})
     */
    protected $pieces;

    /**
     * Whether the player is offering draw or not
     *
     * @var bool
     * @orm:Column(type="boolean")
     */
    protected $isOfferingDraw = false;

    /**
     * the player current game
     *
     * @var Game
     * @orm:ManyToOne(targetEntity="Game", inversedBy="players")
     */
    protected $game;

    protected function getStackInstance()
    {
        return new Stack();
    }
}

Form/AnybodyGameConfig.php
<?php

namespace Bundle\LichessBundle\Form;
use Bundle\LichessBundle\Model\Game;
use Symfony\Component\Validator\Constraints;
use Symfony\Component\Validator\Mapping\ClassMetadata;

class AnybodyGameConfig extends GameConfig
{
    public $modes = array(0, 1);
    public $times = array(20, 0);
    public $variants = array(Game::VARIANT_STANDARD);

    public function getCountTimes()
    {
        return count($this->times);
    }

    public function getCountVariants()
    {
        return count($this->variants);
    }

    public function getCountModes()
    {
        return count($this->modes);
    }

    public function getTimeNames()
    {
        $names = array();
        foreach($this->times as $time) {
            $names[] = $this->renameTime($time);
        }

        return $names;
    }

    public function getVariantNames()
    {
        $variantNames = Game::getVariantNames();
        $names = array();
        foreach($this->variants as $variant) {
            $names[] = ucfirst($variantNames[$variant]);
        }

        return $names;
    }

    public function getModeNames()
    {
        $names = array();
        foreach($this->modes as $mode) {
            $names[] = $this->modeChoices[$mode];
        }

        return $names;
    }

    public static function loadValidatorMetadata(ClassMetadata $metadata)
    {
        $metadata->addGetterConstraint('countTimes', new Constraints\Min(array('limit' => 1)));
        $metadata->addGetterConstraint('countVariants', new Constraints\Min(array('limit' => 1)));
        $metadata->addGetterConstraint('countModes', new Constraints\Min(array('limit' => 1)));
    }

    public function toArray()
    {
        return array('times' => $this->times, 'variants' => $this->variants, 'modes' => $this->modes);
    }

    public function fromArray(array $data)
    {
        if(isset($data['times'])) $this->times = $data['times'];
        if(isset($data['variants'])) $this->variants = $data['variants'];
        if(isset($data['modes'])) $this->modes = $data['modes'];
    }
}

Form/FriendGameConfig.php
<?php

namespace Bundle\LichessBundle\Form;
use Bundle\LichessBundle\Model\Game;
use Symfony\Component\Validator\Constraints;
use Symfony\Component\Validator\Mapping\ClassMetadata;

class FriendGameConfig extends GameConfig
{
    public $time = 0;
    public $variant = Game::VARIANT_STANDARD;
    public $mode = 0;

    public static function loadValidatorMetadata(ClassMetadata $metadata)
    {
        $metadata->addPropertyConstraint('time', new Constraints\Min(array('limit' => 0)));
    }

    public function getTimeName()
    {
        return $this->renameTime($this->time);
    }

    public function getVariantName()
    {
        $variantNames = Game::getVariantNames();

        return ucfirst($variantNames[$this->variant]);
    }

    public function getModeName()
    {
        return $this->modeChoices[$this->mode];
    }

    public function toArray()
    {
        return array('time' => $this->time, 'variant' => $this->variant, 'mode' => $this->mode);
    }

    public function fromArray(array $data)
    {
        if(isset($data['time'])) $this->time = $data['time'];
        if(isset($data['variant'])) $this->variant = $data['variant'];
        if(isset($data['mode'])) $this->mode = $data['mode'];
    }
}

Controller/PlayerController.php
<?php

namespace Bundle\LichessBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Bundle\LichessBundle\Chess\Analyser;
use Bundle\LichessBundle\Chess\Manipulator;
use Bundle\LichessBundle\Model\Game;
use Bundle\LichessBundle\Form;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\HttpKernel\Exception\HttpException;

class PlayerController extends Controller
{
    public function outoftimeAction($id, $version)
    {
        return $this->renderJson($this->get('lichess_service_player')->checkOutOfTime($id, $version));
    }

    public function rematchAction($id)
    {
        $player = $this->get('lichess_service_player')->rematch($id);

        return $this->redirect($this->generateUrl('lichess_player', array('id' => $player->getFullId())));
    }

    public function syncAction($id, $color, $version, $playerFullId)
    {
        $data = $this->get('lichess_service_player')->sync($id, $color, $playerFullId, $version);
        // remove private events if user is spectator
        if(!$playerFullId) {
            foreach($data['e'] as $index => $event) {
                if('message' === $event['type'] || 'redirect' === $event['type']) {
                    unset($data['e'][$index]);
                }
            }
        }

        return $this->renderJson($data);
    }

    public function forceResignAction($id)
    {

        $this->get('lichess_service_player')->resign($id, true);

        return $this->redirect($this->generateUrl('lichess_player', array('id' => $id)));
    }

    public function offerDrawAction($id)
    {
        if ($this->get('lichess_service_draw')->offer($id)) {
            return $this->redirect($this->generateUrl('lichess_player', array('id' => $id)));
        } else {
            return $this->forward('LichessBundle:Player:acceptDrawOffer', array('id' => $id));
        }
    }

    public function declineDrawOfferAction($id)
    {
        $this->get('lichess_service_draw')->declineOffer($id);

        return $this->redirect($this->generateUrl('lichess_player', array('id' => $id)));
    }

    public function acceptDrawOfferAction($id)
    {
        $this->get('lichess_service_draw')->acceptOffer($id);

        return $this->redirect($this->generateUrl('lichess_player', array('id' => $id)));
    }

    public function cancelDrawOfferAction($id)
    {
        $this->get('lichess_service_draw')->cancelOffer($id);

        return $this->redirect($this->generateUrl('lichess_player', array('id' => $id)));
    }

    public function claimDrawAction($id)
    {

        $this->get('lichess_service_draw')->claimOffer($id);

        return $this->redirect($this->generateUrl('lichess_player', array('id' => $id)));
    }

    public function moveAction($id, $version)
    {
        $postData = $this->get('request')->request;
        $data = $this->get('lichess_service_board')->move($id, $postData->get('from'), $postData->get('to'), $postData->get('options', array()), $version);

        return $this->renderJson($data);
    }

    public function showAction($id)
    {
        $player = $this->get('lichess_service_player')->findPlayer($id);
        $game = $player->getGame();

        $this->get('lichess_synchronizer')->setAlive($player);

        if(!$game->getIsStarted()) {
            throw new HttpException(sprintf('Player:show game:%s, Game not started', $game->getId()), 410);
        }

        $analyser = new Analyser($game->getBoard());
        $isKingAttacked = $analyser->isKingAttacked($game->getTurnPlayer());
        if($isKingAttacked) {
            $checkSquareKey = $game->getTurnPlayer()->getKing()->getSquareKey();
        }
        else {
            $checkSquareKey = null;
        }
        return $this->render('LichessBundle:Player:show.twig', array(
            'player' => $player,
            'isOpponentConnected' => $this->get('lichess_synchronizer')->isConnected($player->getOpponent()),
            'checkSquareKey' => $checkSquareKey,
            'possibleMoves' => ($player->isMyTurn() && $game->getIsPlayable()) ? $analyser->getPlayerPossibleMoves($player, $isKingAttacked) : null
        ));
    }

    /**
     * Add a message to the chat room
     */
    public function sayAction($id, $version)
    {
        if('POST' !== $this->get('request')->getMethod()) {
            throw new NotFoundHttpException(sprintf('Player:say game:%s, POST method required', $id));
        }
        
        $data = $this->get('lichess_service_player')->addMessage($id, trim($this->get('request')->get('message')), $version);

        return $this->renderJson($data);
    }

    public function waitAnybodyAction($id)
    {
        try {
            $player = $this->get('lichess_service_player')->findPlayer($id);
        }
        catch(NotFoundHttpException $e) {
            return $this->redirect($this->generateUrl('lichess_invite_anybody'));
        }
        if($player->getGame()->getIsStarted()) {
            return $this->redirect($this->generateUrl('lichess_player', array('id' => $id)));
        }
        $this->get('lichess_synchronizer')->setAlive($player);

        $config = new Form\AnybodyGameConfig();
        $config->fromArray($this->get('session')->get('lichess.game_config.anybody', array()));
        return $this->render('LichessBundle:Player:waitAnybody.twig', array(
            'player' => $player,
            'config' => $config
        ));
    }

    public function cancelAnybodyAction($id)
    {
        $player = $this->get('lichess_service_player')->findPlayer($id);
        $game   = $player->getGame();
        if($game->getIsStarted()) {
            return $this->redirect($this->generateUrl('lichess_player', array('id' => $id)));
        }
        $this->get('lichess.seek_queue')->remove($game);
        $this->get('lichess.object_manager')->flush();
        $this->get('logger')->notice(sprintf('Game:inviteAnybody cancel game:%s', $game->getId()));

        return $this->redirect($this->generateUrl('lichess_homepage', array('color' => $player->getColor())));
    }

    public function waitFriendAction($id)
    {
        $player = $this->get('lichess_service_player')->findPlayer($id);
        if($player->getGame()->getIsStarted()) {
            return $this->redirect($this->generateUrl('lichess_player', array('id' => $id)));
        }
        $this->get('lichess_synchronizer')->setAlive($player);

        $config = new Form\FriendGameConfig();
        $config->fromArray($this->get('session')->get('lichess.game_config.friend', array()));
        return $this->render('LichessBundle:Player:waitFriend.twig', array(
            'player' => $player,
            'config' => $config
        ));
    }

    public function resignAction($id)
    {
        $this->get('lichess_service_player')->resign($id);

        return $this->redirect($this->generateUrl('lichess_player', array('id' => $id)));
    }

    public function abortAction($id)
    {
        $this->get('lichess_service_player')->abort($id);

        return $this->redirect($this->generateUrl('lichess_player', array('id' => $id)));
    }

    public function aiLevelAction($id)
    {
        $this->get('lichess_service_player')->setAiLevel($id, (int)$this->get('request')->get('level'));

        return $this->createResponse('done');
    }

    public function tableAction($id, $color, $playerFullId)
    {
        if($playerFullId) {
            $player = $this->get('lichess_service_player')->findPlayer($playerFullId);
            $template = $player->getGame()->getIsPlayable() ? 'table' : 'tableEnd';
            
            if($nextPlayerId = $player->getGame()->getNext()) {
                $nextGame = $this->get('lichess_service_player')->findPlayer($nextPlayerId)->getGame();
            }
            else {
                $nextGame = null;
            }
        }
        else {
            $player = $this->get('lichess_service_player')->findPublicPlayer($id, $color);
            $template = 'watchTable';
            $nextGame = null;
        }
        return $this->render('LichessBundle:Game:'.$template.'.twig', array(
            'player'              => $player,
            'isOpponentConnected' => $this->get('lichess_synchronizer')->isConnected($player->getOpponent()),
            'nextGame'            => $nextGame
        ));
    }

    public function opponentAction($id, $color, $playerFullId)
    {
        if($playerFullId) {
            $player = $this->get('lichess_service_player')->findPlayer($playerFullId);
            $template = 'opponent';
        }
        else {
            $player = $this->get('lichess_service_player')->findPublicPlayer($id, $color);
            $template = 'watchOpponent';
        }
        $opponent = $player->getOpponent();
        return $this->render('LichessBundle:Player:'.$template.'.twig', array(
            'opponent'            => $opponent,
            'isOpponentConnected' => $playerFullId ? $this->get('lichess_synchronizer')->isConnected($opponent) : true,
            'game'                => $player->getGame(),
            'playerFullId'        => $playerFullId
        ));
    }

    protected function renderJson($data)
    {
        $response = $this->createResponse(json_encode($data));
        $response->headers->set('Content-Type', 'application/json');
        return $response;
    }
}

Resources/views/Player/layoutPlayer.twig
{% extends "LichessBundle:Game:layoutGame.twig" %}
{% block assets %}
{% parent %}
{% javascript "bundles/lichess/js/game.js" %}
{% endblock %}

Resources/views/Player/opponent.twig
{% set opponentLink %}{{ _view.lichess_user.link(opponent, 'blank_if_play')|raw }}{% endset %}
{% if isOpponentConnected %}
<div title="{% trans "Human opponent connected" %}" class="username connected">{{ opponentLink|raw }}</div>
{% elseif game.isFinishedOrAborted %}
<div title="{% trans "Human opponent offline" %}" class="username offline">{{ opponentLink|raw }}</div>
{% else %}
{{ opponentLink|raw }} - {% trans "The other player has left the game. You can force resignation, or wait for him." %}<br />
<a title="{% trans "Make your opponent resign" %}" class="force_resignation" href="{% path "lichess_force_resignation" with ["id": playerFullId] %}">{% trans "Force resignation" %}</a>
{% endif %}

Resources/views/Player/room.twig
<div class="lichess_chat">
    <div class="lichess_chat_inner">
        <input title="{% trans "Toggle the chat" %}" class="toggle_chat" type="checkbox" checked="checked" />
        <ol class="lichess_messages">
            {{ _view.lichess.roomMessages(player.game.room.messages)|raw }}
        </ol>
        <form action="" method="post">
            <input class="lichess_say lichess_hint" value="{% trans "Talk in chat" %}" />
            <a class="send"></a>
        </form>
    </div>
</div>

Resources/views/Player/show.twig
{% extends "LichessBundle:Player:layoutPlayer.twig" %}
{% block robots %}noindex, nofollow{% endblock %}
{% block title_suffix %} #{{ player.fullId }}{% endblock %}
{% block content %}
<div class="lichess_game clearfix lichess_player_{{ player.color }} not_spectator">
    <div class="lichess_board_wrap">
        {{ _view.lichess_game.renderBoard(player, checkSquareKey)|raw }}
    </div>
    <div class="lichess_ground">
        {% include "LichessBundle:Game:cemetery.twig" with ["player": player, "position": "top"] %}
        <div class="lichess_table_wrap">
            {% render "LichessBundle:Player:table" with ["id": player.game.id, "color": player.color, "playerFullId": player.fullId] %}
        </div>
        {% include "LichessBundle:Game:cemetery.twig" with ["player": player.opponent, "position": "bottom"] %}
    </div>
</div>
{% endblock %}
{% block goodies %}
    {% include "LichessBundle:Game:goodies.twig" with ["game": player.game, "color": player.color] %}
{% endblock %}
{% block js_data %}
    {{ _view.lichess_game.renderData(player, possibleMoves, isOpponentConnected)|raw }}
{% endblock %}
{% block chat %}
{% if player.opponent.isHuman %}{% include "LichessBundle:Player:room.twig" with ["player": player] %}{% endif %}
{% endblock %}

Resources/views/Player/waitAnybody.twig
{% extends "LichessBundle:Player:layoutPlayer.twig" %}
{% block title %}Lichess - {% trans "Play with anybody" %} - {{ player.color }}{% endblock %}
{% block content %}
<div class="lichess_game lichess_game_not_started waiting_opponent clearfix lichess_player_{{ player.color }}">
    <div class="lichess_board_wrap">
        {% include "LichessBundle:Main:staticBoard_" ~ player.color ~ ".twig" %}
        <div class="lichess_overboard wait_anybody">
            <img src="{% asset 'bundles/lichess/images/hloader.gif' %}" width="220" height="33" /><br />
            {% trans 'Waiting for opponent' %}...
            <a class="cancel" href="{% path "lichess_cancel_anybody" with["id": player.fullId] %}">{% trans "Cancel" %}</a>
            <p class="explanations">
                {% trans "Variant" %}: {{ _view.lichess_config.choices(config.variantNames)|raw }}<br />
                {% trans "Minutes per side" %}: {{ _view.lichess_config.choices(config.timeNames)|raw }}<br />
                {% trans "Mode" %}: {{ _view.lichess_config.choices(config.modeNames)|raw }}
            </p>
            <p class="explanations">
                {% trans "Hold on, we are searching for a game that matches your criteria" %}
            </p>
        </div>
    </div>
    {% include "LichessBundle:Game:bootGround.twig" with ["color": player.color, "active": "anybody"] %}
</div>
{% endblock %}
{% block js_data %}
    {{ _view.lichess_game.renderData(player, null, false)|raw }}
{% endblock %}

Resources/views/Player/waitFriend.twig
{% extends "LichessBundle:Player:layoutPlayer.twig" %}
{% block title %}Lichess - {% trans "Play with a friend" %} - {{ player.color }}{% endblock %}
{% block content %}
<div class="lichess_game lichess_game_not_started waiting_opponent clearfix lichess_player_{{ player.color }}">
    <div class="lichess_board_wrap">
        {% include "LichessBundle:Main:staticBoard_" ~ player.color ~ ".twig" %}
        <div class="lichess_overboard">
            {% trans "To invite someone to play, give this url" %}:
            <input class="lichess_id_input" readonly="readonly" value="{% url "lichess_game" with ["id": player.game.id] %}" />
            <p class="explanations">{% trans "The first person to come on this url will play with you." %}<p>
            <p class="explanations">
                {% trans "Variant" %}: {% trans config.variantName %}<br />
                {% trans "Minutes per side" %}: {% trans config.timeName %}<br />
                {% trans "Mode" %}: {% trans config.modeName %}
            </p>
        </div>
    </div>
    {% include "LichessBundle:Game:bootGround.twig" with ["color": player.color, "active": "friend"] %}
</div>
{% endblock %}
{% block js_data %}
    {{ _view.lichess_game.renderData(player, null, false)|raw }}
{% endblock %}

Resources/views/Player/watch.twig
{% extends "LichessBundle:Player:layoutPlayer.twig" %}
{% block title_suffix %} #{{ player.game.id }}{% endblock %}
{% block content %}
<div class="lichess_game clearfix lichess_player_{{ player.color }}">
    <div class="lichess_board_wrap">
        {{ _view.lichess_game.renderBoard(player, checkSquareKey)|raw }}
    </div>
    <div class="lichess_ground">
        {% include "LichessBundle:Game:cemetery.twig" with ["player": player, "position": "top"] %}
        <div class="lichess_table_wrap">
            {% render "LichessBundle:Player:table" with ["id": player.game.id, "color": player.color, "playerFullId": ""] %}
        </div>
        {% include "LichessBundle:Game:cemetery.twig" with ["player": player.opponent, "position": "bottom"] %}
    </div>
</div>
{% endblock %}
{% block js_data %}
    {{ _view.lichess_game.renderWatchData(player, possibleMoves)|raw }}
{% endblock %}
{% block goodies %}
<div class="lichess_goodies">
    <a class="lichess_replay_link" href="{% path "lichess_pgn_viewer" with ["id": player.game.id, "color": player.color] %}">{% trans "Replay and analyse" %}</a>
    <br /><br />
    {% trans "You are viewing this game as a spectator" %}.<br /><br />
    <a href="{% path "lichess_homepage" %}"><strong>{% trans "Play a new game" %}</strong></a>
</div>
{% endblock %}

Resources/views/Player/watchOpponent.twig
{% if opponent.isAi %}
{% trans "%ai_name% level %ai_level%" with ['%ai_name%': 'Crafty A.I.', '%ai_level%': opponent.aiLevel] %}
{% else %}
<div title="{% trans "Human opponent " ~ isOpponentConnected ? "connected" : "offline" %}" class="username">
    {% trans opponent.color|capitalize %} - {{ _view.lichess_user.link(opponent)|raw }}
</div>
{% endif %}